# Provide instructions for google Cloud Build to build and upload the flutter
# dashboard docker image to artifact registry.

steps:
  # Build docker image
  - name: 'us-docker.pkg.dev/cloud-builders/ga/v1/docker'
    args: ['build', '-t', 'us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA', '.']

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        gcloud builds submit \
          --config cloudbuild_deploy.yaml \
          --substitutions="SHORT_SHA=$SHORT_SHA" \
          --async

timeout: 1200s

images: ['us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA']

# If build provenance is not generated, the docker deployment will fail.
options:
  requestedVerifyOption: VERIFIED
