# Provide instructions for google Cloud Build to build and upload the flutter
# dashboard docker image to artifact registry.

steps:
  - name: gcr.io/$PROJECT_ID/firebase
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        firebase hosting:channel:deploy --expires 7d pr$_PR_NUMBER-$_HEAD_BRANCH --project=$PROJECT_ID

        echo "Installing jq using apt..."
        apt update && apt install -y jq

        STAGING_URL=$$(firebase hosting:channel:list --json | jq '.result.channels[]|select(.name|contains("drewroen-sandbox-pr7-new-branch")) | .url')

        apt update && apt install -y \
        curl \
        gpg
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg;
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null;
        apt update && apt install -y gh;

        echo "Try and get the token now"
        echo $$GH_PAT_TOKEN > token
        gh auth login --with-token < token
        gh pr comment $_PR_NUMBER --body "Deployed to: $$STAGING_URL" --repo drewroengoogle/test-script
    secretEnv: ['GH_PAT_TOKEN']
  # - name: gcr.io/cloud-builders/gcloud
  #   entrypoint: '/bin/bash'
  #   args:
  #     - '-c'
  #     - |-

availableSecrets:
  secretManager:
  - versionName: projects/drewroen-sandbox/secrets/gh_token_comment/versions/latest
    env: 'GH_PAT_TOKEN'
timeout: 1200s
