steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        gcloud artifacts docker images describe \
          us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA:latest \
          --show-provenance --format json \
          > unverified-provenance.json
        
  - name: 'golang:stretch'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        ./verify-slsa-provenance.sh
timeout: 1200s
