# Provide instructions for google Cloud Build to build and upload the flutter
# dashboard docker image to artifact registry.

steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        gh

timeout: 1200s
