steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        gcloud artifacts docker images describe us-docker.pkg.dev/drewroen-sandbox/appengine/default.version-12345:latest --show-provenance
        
  - name: 'golang:stretch'
    entrypoint: 'go'
    args: ['install', 'github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.0.1']
    
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        slsa-verifier version
timeout: 1200s
