steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        apt-get install jq -y
        jq
        gcloud artifacts docker images describe \
          us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA:latest \
          --show-provenance --format json \
          > unverified-provenance.json
        gcloud artifacts docker images describe \
          us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA:latest \
           | grep fully_qualified_digest \
           | cut -c 27- \
           > DOCKER_DIGEST_URL
        
  - name: 'golang:stretch'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        echo $(cat DOCKER_DIGEST_URL)
        echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        bash verify-slsa-provenance.sh $PROJECT_ID $SHORT_SHA $(cat DOCKER_DIGEST_URL)
timeout: 1200s
