steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        gcloud artifacts docker images describe \
          us-docker.pkg.dev/$PROJECT_ID/appengine/default.version-$SHORT_SHA:latest \
          --show-provenance --format json \
          > unverified-provenance.json
        
  - name: 'golang:stretch'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |-
        curl -sLo jq "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" && chmod +x jq
        bash verify-slsa-provenance.sh \
          $(cat unverified-provenance.json | ./jq -r .image_summary.fully_qualified_digest)
timeout: 1200s
